services:
  backend:
    build:
      context: ./src/backend
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app

  frontend:
    build:
      context: ./src/frontend
    command: pnpm dev --hostname 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend
