[pytest]
asyncio_mode = auto
asyncio_default_test_loop_scope = function
pythonpath = . ..
testpaths = tests
markers =
    unit: Unit tests
    integration: Integration tests
    contract: Contract tests
    e2e: E2E tests
