/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UrlImportRequest
 */
export interface UrlImportRequest {
    /**
     * URL to import from
     * @type {string}
     * @memberof UrlImportRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof UrlImportRequest
     */
    strategy?: string | null;
}

/**
 * Check if a given object implements the UrlImportRequest interface.
 */
export function instanceOfUrlImportRequest(value: object): value is UrlImportRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function UrlImportRequestFromJSON(json: any): UrlImportRequest {
    return UrlImportRequestFromJSONTyped(json, false);
}

export function UrlImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'strategy': json['strategy'] == null ? undefined : json['strategy'],
    };
}

export function UrlImportRequestToJSON(json: any): UrlImportRequest {
    return UrlImportRequestToJSONTyped(json, false);
}

export function UrlImportRequestToJSONTyped(value?: UrlImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'strategy': value['strategy'],
    };
}

