/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceCreate
 */
export interface WorkspaceCreate {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkspaceCreate
     */
    embedding?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkspaceCreate
     */
    retrieval?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkspaceCreate
     */
    generation?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkspaceCreate
     */
    chunking?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    embeddingProvider?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    embeddingModel?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    embeddingDim?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    ragEngine?: WorkspaceCreateRagEngineEnum;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    searchLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    recallK?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    hybridAlpha?: number;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceCreate
     */
    graphEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceCreate
     */
    rerankerEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    rerankerProvider?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    rerankTopK?: number;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceCreate
     */
    agenticEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    llmProvider?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    llmModel?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    temperature?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    runtimeMode?: WorkspaceCreateRuntimeModeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceCreate
     */
    runtimeStreamThoughts?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    runtimeTraceLevel?: WorkspaceCreateRuntimeTraceLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    chunkingStrategy?: WorkspaceCreateChunkingStrategyEnum;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    chunkSize?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceCreate
     */
    chunkOverlap?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    neo4jUri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    neo4jUser?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreate
     */
    neo4jPassword?: string | null;
}


/**
 * @export
 */
export const WorkspaceCreateRagEngineEnum = {
    Basic: 'basic',
    Graph: 'graph'
} as const;
export type WorkspaceCreateRagEngineEnum = typeof WorkspaceCreateRagEngineEnum[keyof typeof WorkspaceCreateRagEngineEnum];

/**
 * @export
 */
export const WorkspaceCreateRuntimeModeEnum = {
    Auto: 'auto',
    Fast: 'fast',
    Think: 'think',
    Deep: 'deep'
} as const;
export type WorkspaceCreateRuntimeModeEnum = typeof WorkspaceCreateRuntimeModeEnum[keyof typeof WorkspaceCreateRuntimeModeEnum];

/**
 * @export
 */
export const WorkspaceCreateRuntimeTraceLevelEnum = {
    Basic: 'basic',
    Detailed: 'detailed',
    Debug: 'debug'
} as const;
export type WorkspaceCreateRuntimeTraceLevelEnum = typeof WorkspaceCreateRuntimeTraceLevelEnum[keyof typeof WorkspaceCreateRuntimeTraceLevelEnum];

/**
 * @export
 */
export const WorkspaceCreateChunkingStrategyEnum = {
    Recursive: 'recursive',
    Sentence: 'sentence',
    Token: 'token',
    Semantic: 'semantic',
    Fixed: 'fixed',
    Document: 'document'
} as const;
export type WorkspaceCreateChunkingStrategyEnum = typeof WorkspaceCreateChunkingStrategyEnum[keyof typeof WorkspaceCreateChunkingStrategyEnum];


/**
 * Check if a given object implements the WorkspaceCreate interface.
 */
export function instanceOfWorkspaceCreate(value: object): value is WorkspaceCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WorkspaceCreateFromJSON(json: any): WorkspaceCreate {
    return WorkspaceCreateFromJSONTyped(json, false);
}

export function WorkspaceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'embedding': json['embedding'] == null ? undefined : json['embedding'],
        'retrieval': json['retrieval'] == null ? undefined : json['retrieval'],
        'generation': json['generation'] == null ? undefined : json['generation'],
        'chunking': json['chunking'] == null ? undefined : json['chunking'],
        'embeddingProvider': json['embedding_provider'] == null ? undefined : json['embedding_provider'],
        'embeddingModel': json['embedding_model'] == null ? undefined : json['embedding_model'],
        'embeddingDim': json['embedding_dim'] == null ? undefined : json['embedding_dim'],
        'ragEngine': json['rag_engine'] == null ? undefined : json['rag_engine'],
        'searchLimit': json['search_limit'] == null ? undefined : json['search_limit'],
        'recallK': json['recall_k'] == null ? undefined : json['recall_k'],
        'hybridAlpha': json['hybrid_alpha'] == null ? undefined : json['hybrid_alpha'],
        'graphEnabled': json['graph_enabled'] == null ? undefined : json['graph_enabled'],
        'rerankerEnabled': json['reranker_enabled'] == null ? undefined : json['reranker_enabled'],
        'rerankerProvider': json['reranker_provider'] == null ? undefined : json['reranker_provider'],
        'rerankTopK': json['rerank_top_k'] == null ? undefined : json['rerank_top_k'],
        'agenticEnabled': json['agentic_enabled'] == null ? undefined : json['agentic_enabled'],
        'llmProvider': json['llm_provider'] == null ? undefined : json['llm_provider'],
        'llmModel': json['llm_model'] == null ? undefined : json['llm_model'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'runtimeMode': json['runtime_mode'] == null ? undefined : json['runtime_mode'],
        'runtimeStreamThoughts': json['runtime_stream_thoughts'] == null ? undefined : json['runtime_stream_thoughts'],
        'runtimeTraceLevel': json['runtime_trace_level'] == null ? undefined : json['runtime_trace_level'],
        'chunkingStrategy': json['chunking_strategy'] == null ? undefined : json['chunking_strategy'],
        'chunkSize': json['chunk_size'] == null ? undefined : json['chunk_size'],
        'chunkOverlap': json['chunk_overlap'] == null ? undefined : json['chunk_overlap'],
        'neo4jUri': json['neo4j_uri'] == null ? undefined : json['neo4j_uri'],
        'neo4jUser': json['neo4j_user'] == null ? undefined : json['neo4j_user'],
        'neo4jPassword': json['neo4j_password'] == null ? undefined : json['neo4j_password'],
    };
}

export function WorkspaceCreateToJSON(json: any): WorkspaceCreate {
    return WorkspaceCreateToJSONTyped(json, false);
}

export function WorkspaceCreateToJSONTyped(value?: WorkspaceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'embedding': value['embedding'],
        'retrieval': value['retrieval'],
        'generation': value['generation'],
        'chunking': value['chunking'],
        'embedding_provider': value['embeddingProvider'],
        'embedding_model': value['embeddingModel'],
        'embedding_dim': value['embeddingDim'],
        'rag_engine': value['ragEngine'],
        'search_limit': value['searchLimit'],
        'recall_k': value['recallK'],
        'hybrid_alpha': value['hybridAlpha'],
        'graph_enabled': value['graphEnabled'],
        'reranker_enabled': value['rerankerEnabled'],
        'reranker_provider': value['rerankerProvider'],
        'rerank_top_k': value['rerankTopK'],
        'agentic_enabled': value['agenticEnabled'],
        'llm_provider': value['llmProvider'],
        'llm_model': value['llmModel'],
        'temperature': value['temperature'],
        'runtime_mode': value['runtimeMode'],
        'runtime_stream_thoughts': value['runtimeStreamThoughts'],
        'runtime_trace_level': value['runtimeTraceLevel'],
        'chunking_strategy': value['chunkingStrategy'],
        'chunk_size': value['chunkSize'],
        'chunk_overlap': value['chunkOverlap'],
        'neo4j_uri': value['neo4jUri'],
        'neo4j_user': value['neo4jUser'],
        'neo4j_password': value['neo4jPassword'],
    };
}

