apiVersion: v1
kind: Service
metadata:
  name: rag-platform-backend
spec:
  selector:
    app: rag-platform-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
