apiVersion: v1
kind: Service
metadata:
  name: rag-platform-frontend
spec:
  selector:
    app: rag-platform-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
