/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeleteThreadChatThreadsThreadIdDeleteRequest {
    threadId: string;
}

export interface GetChatHistoryChatHistoryThreadIdGetRequest {
    threadId: string;
}

export interface ListChatThreadsChatThreadsGetRequest {
    workspaceId?: string;
}

export interface UpdateThreadTitleChatThreadsThreadIdTitlePatchRequest {
    threadId: string;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Chat Stream
     */
    async chatStreamChatStreamPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Chat Stream
     */
    async chatStreamChatStreamPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.chatStreamChatStreamPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete Thread
     */
    async deleteThreadChatThreadsThreadIdDeleteRaw(requestParameters: DeleteThreadChatThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling deleteThreadChatThreadsThreadIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Thread
     */
    async deleteThreadChatThreadsThreadIdDelete(requestParameters: DeleteThreadChatThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteThreadChatThreadsThreadIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Chat History
     */
    async getChatHistoryChatHistoryThreadIdGetRaw(requestParameters: GetChatHistoryChatHistoryThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getChatHistoryChatHistoryThreadIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/history/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Chat History
     */
    async getChatHistoryChatHistoryThreadIdGet(requestParameters: GetChatHistoryChatHistoryThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getChatHistoryChatHistoryThreadIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Chat Threads
     */
    async listChatThreadsChatThreadsGetRaw(requestParameters: ListChatThreadsChatThreadsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/threads`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Chat Threads
     */
    async listChatThreadsChatThreadsGet(requestParameters: ListChatThreadsChatThreadsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listChatThreadsChatThreadsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Thread Title
     */
    async updateThreadTitleChatThreadsThreadIdTitlePatchRaw(requestParameters: UpdateThreadTitleChatThreadsThreadIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateThreadTitleChatThreadsThreadIdTitlePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/threads/{thread_id}/title`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Thread Title
     */
    async updateThreadTitleChatThreadsThreadIdTitlePatch(requestParameters: UpdateThreadTitleChatThreadsThreadIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateThreadTitleChatThreadsThreadIdTitlePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
