/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeleteDocumentDocumentsNameDeleteRequest {
    name: string;
    workspaceId?: string;
    vaultDelete?: boolean;
}

export interface GetDocumentChunksDocumentsNameChunksGetRequest {
    name: string;
    limit?: number;
}

export interface GetDocumentDocumentsNameGetRequest {
    name: string;
}

export interface IndexDocumentDocumentsNameIndexPostRequest {
    name: string;
    workspaceId?: string;
}

export interface InspectDocumentDocumentsNameInspectGetRequest {
    name: string;
}

export interface ListDocumentsDocumentsGetRequest {
    workspaceId?: string;
}

export interface UploadArxivDocumentUploadArxivPostRequest {
    workspaceId?: string;
}

export interface UploadDocumentUploadPostRequest {
    file: Blob;
    workspaceId?: string;
    strategy?: string | null;
}

/**
 * 
 */
export class DocumentsApi extends runtime.BaseAPI {

    /**
     * Delete Document
     */
    async deleteDocumentDocumentsNameDeleteRaw(requestParameters: DeleteDocumentDocumentsNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteDocumentDocumentsNameDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        if (requestParameters['vaultDelete'] != null) {
            queryParameters['vault_delete'] = requestParameters['vaultDelete'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Document
     */
    async deleteDocumentDocumentsNameDelete(requestParameters: DeleteDocumentDocumentsNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteDocumentDocumentsNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document Chunks
     */
    async getDocumentChunksDocumentsNameChunksGetRaw(requestParameters: GetDocumentChunksDocumentsNameChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getDocumentChunksDocumentsNameChunksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{name}/chunks`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Document Chunks
     */
    async getDocumentChunksDocumentsNameChunksGet(requestParameters: GetDocumentChunksDocumentsNameChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDocumentChunksDocumentsNameChunksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document
     */
    async getDocumentDocumentsNameGetRaw(requestParameters: GetDocumentDocumentsNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getDocumentDocumentsNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Document
     */
    async getDocumentDocumentsNameGet(requestParameters: GetDocumentDocumentsNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDocumentDocumentsNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Non-blocking indexing: returns a task_id immediately.  The actual embedding and vector storage runs in the background. Poll GET /tasks/{task_id} for progress.
     * Index Document
     */
    async indexDocumentDocumentsNameIndexPostRaw(requestParameters: IndexDocumentDocumentsNameIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling indexDocumentDocumentsNameIndexPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{name}/index`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Non-blocking indexing: returns a task_id immediately.  The actual embedding and vector storage runs in the background. Poll GET /tasks/{task_id} for progress.
     * Index Document
     */
    async indexDocumentDocumentsNameIndexPost(requestParameters: IndexDocumentDocumentsNameIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.indexDocumentDocumentsNameIndexPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Inspect Document
     */
    async inspectDocumentDocumentsNameInspectGetRaw(requestParameters: InspectDocumentDocumentsNameInspectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling inspectDocumentDocumentsNameInspectGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{name}/inspect`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Inspect Document
     */
    async inspectDocumentDocumentsNameInspectGet(requestParameters: InspectDocumentDocumentsNameInspectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.inspectDocumentDocumentsNameInspectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List All Documents
     */
    async listAllDocumentsDocumentsAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents-all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List All Documents
     */
    async listAllDocumentsDocumentsAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listAllDocumentsDocumentsAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Documents
     */
    async listDocumentsDocumentsGetRaw(requestParameters: ListDocumentsDocumentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Documents
     */
    async listDocumentsDocumentsGet(requestParameters: ListDocumentsDocumentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listDocumentsDocumentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Vault Documents
     */
    async listVaultDocumentsVaultGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vault`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Vault Documents
     */
    async listVaultDocumentsVaultGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listVaultDocumentsVaultGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Non-blocking workspace operations (link, move, share).  Returns a task_id immediately for long-running operations (link, move with reindex). Poll GET /tasks/{task_id} for progress.
     * Update Document Workspaces
     */
    async updateDocumentWorkspacesDocumentsUpdateWorkspacesPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/update-workspaces`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Non-blocking workspace operations (link, move, share).  Returns a task_id immediately for long-running operations (link, move with reindex). Poll GET /tasks/{task_id} for progress.
     * Update Document Workspaces
     */
    async updateDocumentWorkspacesDocumentsUpdateWorkspacesPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateDocumentWorkspacesDocumentsUpdateWorkspacesPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Upload Arxiv Document
     */
    async uploadArxivDocumentUploadArxivPostRaw(requestParameters: UploadArxivDocumentUploadArxivPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/upload-arxiv`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload Arxiv Document
     */
    async uploadArxivDocumentUploadArxivPost(requestParameters: UploadArxivDocumentUploadArxivPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadArxivDocumentUploadArxivPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Document
     */
    async uploadDocumentUploadPostRaw(requestParameters: UploadDocumentUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadDocumentUploadPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        if (requestParameters['strategy'] != null) {
            queryParameters['strategy'] = requestParameters['strategy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload Document
     */
    async uploadDocumentUploadPost(requestParameters: UploadDocumentUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadDocumentUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
