/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CancelTaskTasksTaskIdCancelPostRequest {
    taskId: string;
}

export interface CleanupTasksTasksCleanupDeleteRequest {
    olderThanHours?: number;
}

export interface GetTaskStatusTasksTaskIdGetRequest {
    taskId: string;
}

export interface ListTasksTasksGetRequest {
    type?: string;
    workspaceId?: string;
}

export interface RetryTaskTasksTaskIdRetryPostRequest {
    taskId: string;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Cancel a pending or processing task.
     * Cancel Task
     */
    async cancelTaskTasksTaskIdCancelPostRaw(requestParameters: CancelTaskTasksTaskIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling cancelTaskTasksTaskIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tasks/{task_id}/cancel`;
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Cancel a pending or processing task.
     * Cancel Task
     */
    async cancelTaskTasksTaskIdCancelPost(requestParameters: CancelTaskTasksTaskIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.cancelTaskTasksTaskIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove completed/failed tasks older than the given number of hours.
     * Cleanup Tasks
     */
    async cleanupTasksTasksCleanupDeleteRaw(requestParameters: CleanupTasksTasksCleanupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['olderThanHours'] != null) {
            queryParameters['older_than_hours'] = requestParameters['olderThanHours'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tasks/cleanup`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Remove completed/failed tasks older than the given number of hours.
     * Cleanup Tasks
     */
    async cleanupTasksTasksCleanupDelete(requestParameters: CleanupTasksTasksCleanupDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.cleanupTasksTasksCleanupDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the current status of a specific task.
     * Get Task Status
     */
    async getTaskStatusTasksTaskIdGetRaw(requestParameters: GetTaskStatusTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getTaskStatusTasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get the current status of a specific task.
     * Get Task Status
     */
    async getTaskStatusTasksTaskIdGet(requestParameters: GetTaskStatusTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getTaskStatusTasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List tasks, optionally filtered by type and workspace.
     * List Tasks
     */
    async listTasksTasksGetRaw(requestParameters: ListTasksTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tasks/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List tasks, optionally filtered by type and workspace.
     * List Tasks
     */
    async listTasksTasksGet(requestParameters: ListTasksTasksGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listTasksTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Mark a failed task as retryable and re-dispatch it to background workers.
     * Retry Task
     */
    async retryTaskTasksTaskIdRetryPostRaw(requestParameters: RetryTaskTasksTaskIdRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling retryTaskTasksTaskIdRetryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tasks/{task_id}/retry`;
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Mark a failed task as retryable and re-dispatch it to background workers.
     * Retry Task
     */
    async retryTaskTasksTaskIdRetryPost(requestParameters: RetryTaskTasksTaskIdRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.retryTaskTasksTaskIdRetryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
