/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ToolDefinition,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ToolDefinitionFromJSON,
    ToolDefinitionToJSON,
} from '../models/index';

export interface AddToolToolsPostRequest {
    toolDefinition: ToolDefinition;
}

export interface DeleteToolToolsToolIdDeleteRequest {
    toolId: string;
}

export interface ToggleToolToolsToolIdTogglePostRequest {
    toolId: string;
    enabled: boolean;
}

/**
 * 
 */
export class ToolsApi extends runtime.BaseAPI {

    /**
     * Register a new tool (Custom/MCP).
     * Add Tool
     */
    async addToolToolsPostRaw(requestParameters: AddToolToolsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolDefinition>> {
        if (requestParameters['toolDefinition'] == null) {
            throw new runtime.RequiredError(
                'toolDefinition',
                'Required parameter "toolDefinition" was null or undefined when calling addToolToolsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/tools/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToolDefinitionToJSON(requestParameters['toolDefinition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolDefinitionFromJSON(jsonValue));
    }

    /**
     * Register a new tool (Custom/MCP).
     * Add Tool
     */
    async addToolToolsPost(requestParameters: AddToolToolsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolDefinition> {
        const response = await this.addToolToolsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a custom tool.
     * Delete Tool
     */
    async deleteToolToolsToolIdDeleteRaw(requestParameters: DeleteToolToolsToolIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['toolId'] == null) {
            throw new runtime.RequiredError(
                'toolId',
                'Required parameter "toolId" was null or undefined when calling deleteToolToolsToolIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tools/{tool_id}`;
        urlPath = urlPath.replace(`{${"tool_id"}}`, encodeURIComponent(String(requestParameters['toolId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a custom tool.
     * Delete Tool
     */
    async deleteToolToolsToolIdDelete(requestParameters: DeleteToolToolsToolIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteToolToolsToolIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all available tools and their status.
     * List Tools
     */
    async listToolsToolsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ToolDefinition>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tools/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ToolDefinitionFromJSON));
    }

    /**
     * List all available tools and their status.
     * List Tools
     */
    async listToolsToolsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ToolDefinition>> {
        const response = await this.listToolsToolsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Enable or disable a tool.
     * Toggle Tool
     */
    async toggleToolToolsToolIdTogglePostRaw(requestParameters: ToggleToolToolsToolIdTogglePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToolDefinition>> {
        if (requestParameters['toolId'] == null) {
            throw new runtime.RequiredError(
                'toolId',
                'Required parameter "toolId" was null or undefined when calling toggleToolToolsToolIdTogglePost().'
            );
        }

        if (requestParameters['enabled'] == null) {
            throw new runtime.RequiredError(
                'enabled',
                'Required parameter "enabled" was null or undefined when calling toggleToolToolsToolIdTogglePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['enabled'] != null) {
            queryParameters['enabled'] = requestParameters['enabled'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tools/{tool_id}/toggle`;
        urlPath = urlPath.replace(`{${"tool_id"}}`, encodeURIComponent(String(requestParameters['toolId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToolDefinitionFromJSON(jsonValue));
    }

    /**
     * Enable or disable a tool.
     * Toggle Tool
     */
    async toggleToolToolsToolIdTogglePost(requestParameters: ToggleToolToolsToolIdTogglePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToolDefinition> {
        const response = await this.toggleToolToolsToolIdTogglePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
