/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Workspace,
  WorkspaceCreate,
  WorkspaceDetail,
  WorkspaceUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    WorkspaceFromJSON,
    WorkspaceToJSON,
    WorkspaceCreateFromJSON,
    WorkspaceCreateToJSON,
    WorkspaceDetailFromJSON,
    WorkspaceDetailToJSON,
    WorkspaceUpdateFromJSON,
    WorkspaceUpdateToJSON,
} from '../models/index';

export interface CreateWorkspaceWorkspacesPostRequest {
    workspaceCreate: WorkspaceCreate;
}

export interface CreateWorkspaceWorkspacesPost0Request {
    workspaceCreate: WorkspaceCreate;
}

export interface DeleteWorkspaceWorkspacesWorkspaceIdDeleteRequest {
    workspaceId: string;
    vaultDelete?: boolean;
}

export interface GetWorkspaceDetailsWorkspacesWorkspaceIdDetailsGetRequest {
    workspaceId: string;
}

export interface GetWorkspaceGraphWorkspacesWorkspaceIdGraphGetRequest {
    workspaceId: string;
}

export interface ShareDocumentWorkspacesWorkspaceIdShareDocumentPostRequest {
    workspaceId: string;
}

export interface UpdateWorkspaceWorkspacesWorkspaceIdPatchRequest {
    workspaceId: string;
    workspaceUpdate: WorkspaceUpdate;
}

/**
 * 
 */
export class WorkspacesApi extends runtime.BaseAPI {

    /**
     * Create Workspace
     */
    async createWorkspaceWorkspacesPostRaw(requestParameters: CreateWorkspaceWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Workspace>> {
        if (requestParameters['workspaceCreate'] == null) {
            throw new runtime.RequiredError(
                'workspaceCreate',
                'Required parameter "workspaceCreate" was null or undefined when calling createWorkspaceWorkspacesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/workspaces`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkspaceCreateToJSON(requestParameters['workspaceCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceFromJSON(jsonValue));
    }

    /**
     * Create Workspace
     */
    async createWorkspaceWorkspacesPost(requestParameters: CreateWorkspaceWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Workspace> {
        const response = await this.createWorkspaceWorkspacesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Workspace
     */
    async createWorkspaceWorkspacesPost_1Raw(requestParameters: CreateWorkspaceWorkspacesPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Workspace>> {
        if (requestParameters['workspaceCreate'] == null) {
            throw new runtime.RequiredError(
                'workspaceCreate',
                'Required parameter "workspaceCreate" was null or undefined when calling createWorkspaceWorkspacesPost_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/workspaces/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkspaceCreateToJSON(requestParameters['workspaceCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceFromJSON(jsonValue));
    }

    /**
     * Create Workspace
     */
    async createWorkspaceWorkspacesPost_1(requestParameters: CreateWorkspaceWorkspacesPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Workspace> {
        const response = await this.createWorkspaceWorkspacesPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Workspace
     */
    async deleteWorkspaceWorkspacesWorkspaceIdDeleteRaw(requestParameters: DeleteWorkspaceWorkspacesWorkspaceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteWorkspaceWorkspacesWorkspaceIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['vaultDelete'] != null) {
            queryParameters['vault_delete'] = requestParameters['vaultDelete'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workspaces/{workspace_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Workspace
     */
    async deleteWorkspaceWorkspacesWorkspaceIdDelete(requestParameters: DeleteWorkspaceWorkspacesWorkspaceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteWorkspaceWorkspacesWorkspaceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Workspace Details
     */
    async getWorkspaceDetailsWorkspacesWorkspaceIdDetailsGetRaw(requestParameters: GetWorkspaceDetailsWorkspacesWorkspaceIdDetailsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceDetail>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getWorkspaceDetailsWorkspacesWorkspaceIdDetailsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workspaces/{workspace_id}/details`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceDetailFromJSON(jsonValue));
    }

    /**
     * Get Workspace Details
     */
    async getWorkspaceDetailsWorkspacesWorkspaceIdDetailsGet(requestParameters: GetWorkspaceDetailsWorkspacesWorkspaceIdDetailsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceDetail> {
        const response = await this.getWorkspaceDetailsWorkspacesWorkspaceIdDetailsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Workspace Graph
     */
    async getWorkspaceGraphWorkspacesWorkspaceIdGraphGetRaw(requestParameters: GetWorkspaceGraphWorkspacesWorkspaceIdGraphGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getWorkspaceGraphWorkspacesWorkspaceIdGraphGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workspaces/{workspace_id}/graph`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Workspace Graph
     */
    async getWorkspaceGraphWorkspacesWorkspaceIdGraphGet(requestParameters: GetWorkspaceGraphWorkspacesWorkspaceIdGraphGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getWorkspaceGraphWorkspacesWorkspaceIdGraphGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Workspaces
     */
    async listWorkspacesWorkspacesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Workspace>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workspaces`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkspaceFromJSON));
    }

    /**
     * List Workspaces
     */
    async listWorkspacesWorkspacesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Workspace>> {
        const response = await this.listWorkspacesWorkspacesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Workspaces
     */
    async listWorkspacesWorkspacesGet_2Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Workspace>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workspaces/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkspaceFromJSON));
    }

    /**
     * List Workspaces
     */
    async listWorkspacesWorkspacesGet_2(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Workspace>> {
        const response = await this.listWorkspacesWorkspacesGet_2Raw(initOverrides);
        return await response.value();
    }

    /**
     * Share Document
     */
    async shareDocumentWorkspacesWorkspaceIdShareDocumentPostRaw(requestParameters: ShareDocumentWorkspacesWorkspaceIdShareDocumentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling shareDocumentWorkspacesWorkspaceIdShareDocumentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workspaces/{workspace_id}/share-document`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Share Document
     */
    async shareDocumentWorkspacesWorkspaceIdShareDocumentPost(requestParameters: ShareDocumentWorkspacesWorkspaceIdShareDocumentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.shareDocumentWorkspacesWorkspaceIdShareDocumentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Workspace
     */
    async updateWorkspaceWorkspacesWorkspaceIdPatchRaw(requestParameters: UpdateWorkspaceWorkspacesWorkspaceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Workspace>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateWorkspaceWorkspacesWorkspaceIdPatch().'
            );
        }

        if (requestParameters['workspaceUpdate'] == null) {
            throw new runtime.RequiredError(
                'workspaceUpdate',
                'Required parameter "workspaceUpdate" was null or undefined when calling updateWorkspaceWorkspacesWorkspaceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/workspaces/{workspace_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WorkspaceUpdateToJSON(requestParameters['workspaceUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceFromJSON(jsonValue));
    }

    /**
     * Update Workspace
     */
    async updateWorkspaceWorkspacesWorkspaceIdPatch(requestParameters: UpdateWorkspaceWorkspacesWorkspaceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Workspace> {
        const response = await this.updateWorkspaceWorkspacesWorkspaceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
