/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppResponse,
  ChatStreamRequest,
  HTTPValidationError,
  ThreadTitleUpdate,
} from '../models/index';
import {
    AppResponseFromJSON,
    AppResponseToJSON,
    ChatStreamRequestFromJSON,
    ChatStreamRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ThreadTitleUpdateFromJSON,
    ThreadTitleUpdateToJSON,
} from '../models/index';

export interface ChatStreamChatStreamPostRequest {
    chatStreamRequest: ChatStreamRequest;
}

export interface DeleteThreadChatThreadsThreadIdDeleteRequest {
    threadId: string;
}

export interface GetChatHistoryChatHistoryThreadIdGetRequest {
    threadId: string;
}

export interface GetThreadChatThreadsThreadIdGetRequest {
    threadId: string;
}

export interface ListChatThreadsChatThreadsGetRequest {
    workspaceId: string;
}

export interface UpdateThreadTitleChatThreadsThreadIdTitlePatchRequest {
    threadId: string;
    threadTitleUpdate: ThreadTitleUpdate;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Stream chat updates using SSE. Spawns background title generation for consistent UX.
     * Chat Stream
     */
    async chatStreamChatStreamPostRaw(requestParameters: ChatStreamChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatStreamRequest'] == null) {
            throw new runtime.RequiredError(
                'chatStreamRequest',
                'Required parameter "chatStreamRequest" was null or undefined when calling chatStreamChatStreamPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/chat/stream`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatStreamRequestToJSON(requestParameters['chatStreamRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stream chat updates using SSE. Spawns background title generation for consistent UX.
     * Chat Stream
     */
    async chatStreamChatStreamPost(requestParameters: ChatStreamChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.chatStreamChatStreamPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Thread
     */
    async deleteThreadChatThreadsThreadIdDeleteRaw(requestParameters: DeleteThreadChatThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling deleteThreadChatThreadsThreadIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Delete Thread
     */
    async deleteThreadChatThreadsThreadIdDelete(requestParameters: DeleteThreadChatThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.deleteThreadChatThreadsThreadIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Chat History
     */
    async getChatHistoryChatHistoryThreadIdGetRaw(requestParameters: GetChatHistoryChatHistoryThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getChatHistoryChatHistoryThreadIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/history/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Get Chat History
     */
    async getChatHistoryChatHistoryThreadIdGet(requestParameters: GetChatHistoryChatHistoryThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.getChatHistoryChatHistoryThreadIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Thread
     */
    async getThreadChatThreadsThreadIdGetRaw(requestParameters: GetThreadChatThreadsThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getThreadChatThreadsThreadIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Get Thread
     */
    async getThreadChatThreadsThreadIdGet(requestParameters: GetThreadChatThreadsThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.getThreadChatThreadsThreadIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Chat Threads
     */
    async listChatThreadsChatThreadsGetRaw(requestParameters: ListChatThreadsChatThreadsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listChatThreadsChatThreadsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/threads`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * List Chat Threads
     */
    async listChatThreadsChatThreadsGet(requestParameters: ListChatThreadsChatThreadsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.listChatThreadsChatThreadsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Thread Title
     */
    async updateThreadTitleChatThreadsThreadIdTitlePatchRaw(requestParameters: UpdateThreadTitleChatThreadsThreadIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateThreadTitleChatThreadsThreadIdTitlePatch().'
            );
        }

        if (requestParameters['threadTitleUpdate'] == null) {
            throw new runtime.RequiredError(
                'threadTitleUpdate',
                'Required parameter "threadTitleUpdate" was null or undefined when calling updateThreadTitleChatThreadsThreadIdTitlePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/chat/threads/{thread_id}/title`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ThreadTitleUpdateToJSON(requestParameters['threadTitleUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Update Thread Title
     */
    async updateThreadTitleChatThreadsThreadIdTitlePatch(requestParameters: UpdateThreadTitleChatThreadsThreadIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.updateThreadTitleChatThreadsThreadIdTitlePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
