/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppResponse,
  ArxivUploadRequest,
  GitHubImportRequest,
  HTTPValidationError,
  SitemapImportRequest,
  UrlImportRequest,
} from '../models/index';
import {
    AppResponseFromJSON,
    AppResponseToJSON,
    ArxivUploadRequestFromJSON,
    ArxivUploadRequestToJSON,
    GitHubImportRequestFromJSON,
    GitHubImportRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SitemapImportRequestFromJSON,
    SitemapImportRequestToJSON,
    UrlImportRequestFromJSON,
    UrlImportRequestToJSON,
} from '../models/index';

export interface DeleteDocumentDocumentsDocumentIdDeleteRequest {
    documentId: string;
    workspaceId?: string;
    vaultDelete?: boolean;
}

export interface GetDocumentChunksDocumentsDocumentIdChunksGetRequest {
    documentId: string;
    limit?: number;
}

export interface GetDocumentDocumentsDocumentIdGetRequest {
    documentId: string;
}

export interface ImportAudioDocumentImportAudioPostRequest {
    file: Blob;
    workspaceId?: string;
}

export interface ImportGithubDocumentImportGithubPostRequest {
    gitHubImportRequest: GitHubImportRequest;
    workspaceId?: string;
}

export interface ImportSitemapDocumentImportSitemapPostRequest {
    sitemapImportRequest: SitemapImportRequest;
    workspaceId?: string;
}

export interface ImportUrlDocumentImportUrlPostRequest {
    urlImportRequest: UrlImportRequest;
    workspaceId?: string;
}

export interface IndexDocumentDocumentsDocumentIdIndexPostRequest {
    documentId: string;
    workspaceId?: string;
}

export interface InspectDocumentDocumentsDocumentIdInspectGetRequest {
    documentId: string;
}

export interface ListDocumentsDocumentsGetRequest {
    workspaceId?: string;
}

export interface UploadArxivDocumentUploadArxivPostRequest {
    arxivUploadRequest: ArxivUploadRequest;
    workspaceId?: string;
}

export interface UploadDocumentUploadPostRequest {
    file: Blob;
    workspaceId?: string;
    strategy?: string | null;
}

/**
 * 
 */
export class DocumentsApi extends runtime.BaseAPI {

    /**
     * Delete Document
     */
    async deleteDocumentDocumentsDocumentIdDeleteRaw(requestParameters: DeleteDocumentDocumentsDocumentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling deleteDocumentDocumentsDocumentIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        if (requestParameters['vaultDelete'] != null) {
            queryParameters['vault_delete'] = requestParameters['vaultDelete'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{document_id}`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Document
     */
    async deleteDocumentDocumentsDocumentIdDelete(requestParameters: DeleteDocumentDocumentsDocumentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteDocumentDocumentsDocumentIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document Chunks
     */
    async getDocumentChunksDocumentsDocumentIdChunksGetRaw(requestParameters: GetDocumentChunksDocumentsDocumentIdChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getDocumentChunksDocumentsDocumentIdChunksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{document_id}/chunks`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Document Chunks
     */
    async getDocumentChunksDocumentsDocumentIdChunksGet(requestParameters: GetDocumentChunksDocumentsDocumentIdChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDocumentChunksDocumentsDocumentIdChunksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document
     */
    async getDocumentDocumentsDocumentIdGetRaw(requestParameters: GetDocumentDocumentsDocumentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getDocumentDocumentsDocumentIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{document_id}`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Document
     */
    async getDocumentDocumentsDocumentIdGet(requestParameters: GetDocumentDocumentsDocumentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDocumentDocumentsDocumentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Audio Document
     */
    async importAudioDocumentImportAudioPostRaw(requestParameters: ImportAudioDocumentImportAudioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling importAudioDocumentImportAudioPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/import-audio`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Import Audio Document
     */
    async importAudioDocumentImportAudioPost(requestParameters: ImportAudioDocumentImportAudioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.importAudioDocumentImportAudioPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Github Document
     */
    async importGithubDocumentImportGithubPostRaw(requestParameters: ImportGithubDocumentImportGithubPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['gitHubImportRequest'] == null) {
            throw new runtime.RequiredError(
                'gitHubImportRequest',
                'Required parameter "gitHubImportRequest" was null or undefined when calling importGithubDocumentImportGithubPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/import-github`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GitHubImportRequestToJSON(requestParameters['gitHubImportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Import Github Document
     */
    async importGithubDocumentImportGithubPost(requestParameters: ImportGithubDocumentImportGithubPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.importGithubDocumentImportGithubPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Sitemap Document
     */
    async importSitemapDocumentImportSitemapPostRaw(requestParameters: ImportSitemapDocumentImportSitemapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['sitemapImportRequest'] == null) {
            throw new runtime.RequiredError(
                'sitemapImportRequest',
                'Required parameter "sitemapImportRequest" was null or undefined when calling importSitemapDocumentImportSitemapPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/import-sitemap`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SitemapImportRequestToJSON(requestParameters['sitemapImportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Import Sitemap Document
     */
    async importSitemapDocumentImportSitemapPost(requestParameters: ImportSitemapDocumentImportSitemapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.importSitemapDocumentImportSitemapPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Url Document
     */
    async importUrlDocumentImportUrlPostRaw(requestParameters: ImportUrlDocumentImportUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['urlImportRequest'] == null) {
            throw new runtime.RequiredError(
                'urlImportRequest',
                'Required parameter "urlImportRequest" was null or undefined when calling importUrlDocumentImportUrlPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/import-url`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UrlImportRequestToJSON(requestParameters['urlImportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Import Url Document
     */
    async importUrlDocumentImportUrlPost(requestParameters: ImportUrlDocumentImportUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.importUrlDocumentImportUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Non-blocking indexing triggered by document ID.
     * Index Document
     */
    async indexDocumentDocumentsDocumentIdIndexPostRaw(requestParameters: IndexDocumentDocumentsDocumentIdIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling indexDocumentDocumentsDocumentIdIndexPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{document_id}/index`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Non-blocking indexing triggered by document ID.
     * Index Document
     */
    async indexDocumentDocumentsDocumentIdIndexPost(requestParameters: IndexDocumentDocumentsDocumentIdIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.indexDocumentDocumentsDocumentIdIndexPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Inspect Document
     */
    async inspectDocumentDocumentsDocumentIdInspectGetRaw(requestParameters: InspectDocumentDocumentsDocumentIdInspectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling inspectDocumentDocumentsDocumentIdInspectGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/{document_id}/inspect`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Inspect Document
     */
    async inspectDocumentDocumentsDocumentIdInspectGet(requestParameters: InspectDocumentDocumentsDocumentIdInspectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.inspectDocumentDocumentsDocumentIdInspectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List All Documents
     */
    async listAllDocumentsDocumentsAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents-all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List All Documents
     */
    async listAllDocumentsDocumentsAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listAllDocumentsDocumentsAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Documents
     */
    async listDocumentsDocumentsGetRaw(requestParameters: ListDocumentsDocumentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Documents
     */
    async listDocumentsDocumentsGet(requestParameters: ListDocumentsDocumentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listDocumentsDocumentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Vault Documents
     */
    async listVaultDocumentsVaultGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vault`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Vault Documents
     */
    async listVaultDocumentsVaultGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listVaultDocumentsVaultGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Sync Document Workspaces
     */
    async syncDocumentWorkspacesDocumentsSyncWorkspacesPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/sync-workspaces`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Sync Document Workspaces
     */
    async syncDocumentWorkspacesDocumentsSyncWorkspacesPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.syncDocumentWorkspacesDocumentsSyncWorkspacesPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Workspace operations using internal IDs.
     * Update Document Workspaces
     */
    async updateDocumentWorkspacesDocumentsUpdateWorkspacesPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/documents/update-workspaces`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Workspace operations using internal IDs.
     * Update Document Workspaces
     */
    async updateDocumentWorkspacesDocumentsUpdateWorkspacesPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateDocumentWorkspacesDocumentsUpdateWorkspacesPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Upload Arxiv Document
     */
    async uploadArxivDocumentUploadArxivPostRaw(requestParameters: UploadArxivDocumentUploadArxivPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['arxivUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'arxivUploadRequest',
                'Required parameter "arxivUploadRequest" was null or undefined when calling uploadArxivDocumentUploadArxivPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/upload-arxiv`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArxivUploadRequestToJSON(requestParameters['arxivUploadRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Upload Arxiv Document
     */
    async uploadArxivDocumentUploadArxivPost(requestParameters: UploadArxivDocumentUploadArxivPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.uploadArxivDocumentUploadArxivPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Document
     */
    async uploadDocumentUploadPostRaw(requestParameters: UploadDocumentUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadDocumentUploadPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        if (requestParameters['strategy'] != null) {
            queryParameters['strategy'] = requestParameters['strategy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Upload Document
     */
    async uploadDocumentUploadPost(requestParameters: UploadDocumentUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.uploadDocumentUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
