/* tslint:disable */
/* eslint-disable */
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppResponse,
  DocumentWorkspaceUpdate,
  GitHubImportRequest,
  HTTPValidationError,
  SitemapImportRequest,
  UrlImportRequest,
} from '../models/index';
import {
    AppResponseFromJSON,
    AppResponseToJSON,
    DocumentWorkspaceUpdateFromJSON,
    DocumentWorkspaceUpdateToJSON,
    GitHubImportRequestFromJSON,
    GitHubImportRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SitemapImportRequestFromJSON,
    SitemapImportRequestToJSON,
    UrlImportRequestFromJSON,
    UrlImportRequestToJSON,
} from '../models/index';

export interface DeleteDocumentWorkspacesWorkspaceIdDocumentsDocumentIdDeleteRequest {
    documentId: string;
    workspaceId: string;
    vaultDelete?: boolean;
}

export interface GetDocumentChunksWorkspacesWorkspaceIdDocumentsDocumentIdChunksGetRequest {
    documentId: string;
    workspaceId: string;
    limit?: number;
}

export interface GetDocumentWorkspacesWorkspaceIdDocumentsDocumentIdGetRequest {
    documentId: string;
    workspaceId: string;
}

export interface ImportAudioDocumentWorkspacesWorkspaceIdImportAudioPostRequest {
    workspaceId: string;
    file: Blob;
}

export interface ImportGithubDocumentWorkspacesWorkspaceIdImportGithubPostRequest {
    workspaceId: string;
    gitHubImportRequest: GitHubImportRequest;
}

export interface ImportSitemapDocumentWorkspacesWorkspaceIdImportSitemapPostRequest {
    workspaceId: string;
    sitemapImportRequest: SitemapImportRequest;
}

export interface ImportUrlDocumentWorkspacesWorkspaceIdImportUrlPostRequest {
    workspaceId: string;
    urlImportRequest: UrlImportRequest;
}

export interface IndexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPostRequest {
    documentId: string;
    workspaceId: string;
}

export interface InspectDocumentWorkspacesWorkspaceIdDocumentsDocumentIdInspectGetRequest {
    documentId: string;
    workspaceId: string;
}

export interface ListAllDocumentsWorkspacesWorkspaceIdDocumentsAllGetRequest {
    workspaceId: string;
}

export interface ListDocumentsWorkspacesWorkspaceIdDocumentsGetRequest {
    workspaceId: string;
}

export interface ListVaultDocumentsWorkspacesWorkspaceIdVaultGetRequest {
    workspaceId: string;
}

export interface SyncDocumentWorkspacesWorkspacesWorkspaceIdDocumentsSyncWorkspacesPostRequest {
    workspaceId: string;
}

export interface UpdateDocumentWorkspacesWorkspacesWorkspaceIdDocumentsUpdateWorkspacesPostRequest {
    workspaceId: string;
    documentWorkspaceUpdate: DocumentWorkspaceUpdate;
}

export interface UploadDocumentWorkspacesWorkspaceIdUploadPostRequest {
    workspaceId: string;
    file: Blob;
    strategy?: string | null;
}

/**
 * 
 */
export class DocumentsApi extends runtime.BaseAPI {

    /**
     * Delete Document
     */
    async deleteDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdDeleteRaw(requestParameters: DeleteDocumentWorkspacesWorkspaceIdDocumentsDocumentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling deleteDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdDelete().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['vaultDelete'] != null) {
            queryParameters['vault_delete'] = requestParameters['vaultDelete'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents/{document_id}`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Document
     */
    async deleteDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdDelete(requestParameters: DeleteDocumentWorkspacesWorkspaceIdDocumentsDocumentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document Chunks
     */
    async getDocumentChunksApiV1WorkspacesWorkspaceIdDocumentsDocumentIdChunksGetRaw(requestParameters: GetDocumentChunksWorkspacesWorkspaceIdDocumentsDocumentIdChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getDocumentChunksApiV1WorkspacesWorkspaceIdDocumentsDocumentIdChunksGet().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getDocumentChunksApiV1WorkspacesWorkspaceIdDocumentsDocumentIdChunksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents/{document_id}/chunks`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Document Chunks
     */
    async getDocumentChunksApiV1WorkspacesWorkspaceIdDocumentsDocumentIdChunksGet(requestParameters: GetDocumentChunksWorkspacesWorkspaceIdDocumentsDocumentIdChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDocumentChunksApiV1WorkspacesWorkspaceIdDocumentsDocumentIdChunksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document
     */
    async getDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdGetRaw(requestParameters: GetDocumentWorkspacesWorkspaceIdDocumentsDocumentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdGet().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents/{document_id}`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Document
     */
    async getDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdGet(requestParameters: GetDocumentWorkspacesWorkspaceIdDocumentsDocumentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Audio Document
     */
    async importAudioDocumentWorkspacesWorkspaceIdImportAudioPostRaw(requestParameters: ImportAudioDocumentWorkspacesWorkspaceIdImportAudioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling importAudioDocumentWorkspacesWorkspaceIdImportAudioPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling importAudioDocumentWorkspacesWorkspaceIdImportAudioPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/workspaces/{workspace_id}/import-audio`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Import Audio Document
     */
    async importAudioDocumentWorkspacesWorkspaceIdImportAudioPost(requestParameters: ImportAudioDocumentWorkspacesWorkspaceIdImportAudioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.importAudioDocumentWorkspacesWorkspaceIdImportAudioPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Github Document
     */
    async importGithubDocumentApiV1WorkspacesWorkspaceIdImportGithubPostRaw(requestParameters: ImportGithubDocumentWorkspacesWorkspaceIdImportGithubPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling importGithubDocumentApiV1WorkspacesWorkspaceIdImportGithubPost().'
            );
        }

        if (requestParameters['gitHubImportRequest'] == null) {
            throw new runtime.RequiredError(
                'gitHubImportRequest',
                'Required parameter "gitHubImportRequest" was null or undefined when calling importGithubDocumentApiV1WorkspacesWorkspaceIdImportGithubPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/import-github`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GitHubImportRequestToJSON(requestParameters['gitHubImportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Import Github Document
     */
    async importGithubDocumentApiV1WorkspacesWorkspaceIdImportGithubPost(requestParameters: ImportGithubDocumentWorkspacesWorkspaceIdImportGithubPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.importGithubDocumentApiV1WorkspacesWorkspaceIdImportGithubPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Sitemap Document
     */
    async importSitemapDocumentApiV1WorkspacesWorkspaceIdImportSitemapPostRaw(requestParameters: ImportSitemapDocumentWorkspacesWorkspaceIdImportSitemapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling importSitemapDocumentApiV1WorkspacesWorkspaceIdImportSitemapPost().'
            );
        }

        if (requestParameters['sitemapImportRequest'] == null) {
            throw new runtime.RequiredError(
                'sitemapImportRequest',
                'Required parameter "sitemapImportRequest" was null or undefined when calling importSitemapDocumentApiV1WorkspacesWorkspaceIdImportSitemapPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/import-sitemap`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SitemapImportRequestToJSON(requestParameters['sitemapImportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Import Sitemap Document
     */
    async importSitemapDocumentApiV1WorkspacesWorkspaceIdImportSitemapPost(requestParameters: ImportSitemapDocumentWorkspacesWorkspaceIdImportSitemapPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.importSitemapDocumentApiV1WorkspacesWorkspaceIdImportSitemapPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Url Document
     */
    async importUrlDocumentApiV1WorkspacesWorkspaceIdImportUrlPostRaw(requestParameters: ImportUrlDocumentWorkspacesWorkspaceIdImportUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling importUrlDocumentApiV1WorkspacesWorkspaceIdImportUrlPost().'
            );
        }

        if (requestParameters['urlImportRequest'] == null) {
            throw new runtime.RequiredError(
                'urlImportRequest',
                'Required parameter "urlImportRequest" was null or undefined when calling importUrlDocumentApiV1WorkspacesWorkspaceIdImportUrlPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/import-url`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UrlImportRequestToJSON(requestParameters['urlImportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Import Url Document
     */
    async importUrlDocumentApiV1WorkspacesWorkspaceIdImportUrlPost(requestParameters: ImportUrlDocumentWorkspacesWorkspaceIdImportUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.importUrlDocumentApiV1WorkspacesWorkspaceIdImportUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index Document
     */
    async indexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPostRaw(requestParameters: IndexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling indexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPost().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling indexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents/{document_id}/index`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Index Document
     */
    async indexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPost(requestParameters: IndexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.indexDocumentWorkspacesWorkspaceIdDocumentsDocumentIdIndexPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Inspect Document
     */
    async inspectDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdInspectGetRaw(requestParameters: InspectDocumentWorkspacesWorkspaceIdDocumentsDocumentIdInspectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling inspectDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdInspectGet().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling inspectDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdInspectGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents/{document_id}/inspect`;
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Inspect Document
     */
    async inspectDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdInspectGet(requestParameters: InspectDocumentWorkspacesWorkspaceIdDocumentsDocumentIdInspectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.inspectDocumentApiV1WorkspacesWorkspaceIdDocumentsDocumentIdInspectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List All Documents
     */
    async listAllDocumentsApiV1WorkspacesWorkspaceIdDocumentsAllGetRaw(requestParameters: ListAllDocumentsWorkspacesWorkspaceIdDocumentsAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listAllDocumentsApiV1WorkspacesWorkspaceIdDocumentsAllGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents-all`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List All Documents
     */
    async listAllDocumentsApiV1WorkspacesWorkspaceIdDocumentsAllGet(requestParameters: ListAllDocumentsWorkspacesWorkspaceIdDocumentsAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listAllDocumentsApiV1WorkspacesWorkspaceIdDocumentsAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Documents
     */
    async listDocumentsWorkspacesWorkspaceIdDocumentsGetRaw(requestParameters: ListDocumentsWorkspacesWorkspaceIdDocumentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listDocumentsWorkspacesWorkspaceIdDocumentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Documents
     */
    async listDocumentsWorkspacesWorkspaceIdDocumentsGet(requestParameters: ListDocumentsWorkspacesWorkspaceIdDocumentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listDocumentsWorkspacesWorkspaceIdDocumentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Vault Documents
     */
    async listVaultDocumentsWorkspacesWorkspaceIdVaultGetRaw(requestParameters: ListVaultDocumentsWorkspacesWorkspaceIdVaultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listVaultDocumentsWorkspacesWorkspaceIdVaultGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/vault`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Vault Documents
     */
    async listVaultDocumentsWorkspacesWorkspaceIdVaultGet(requestParameters: ListVaultDocumentsWorkspacesWorkspaceIdVaultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listVaultDocumentsWorkspacesWorkspaceIdVaultGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sync Document Workspaces
     */
    async syncDocumentWorkspacesWorkspacesWorkspaceIdDocumentsSyncWorkspacesPostRaw(requestParameters: SyncDocumentWorkspacesWorkspacesWorkspaceIdDocumentsSyncWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling syncDocumentWorkspacesWorkspacesWorkspaceIdDocumentsSyncWorkspacesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents/sync-workspaces`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Sync Document Workspaces
     */
    async syncDocumentWorkspacesWorkspacesWorkspaceIdDocumentsSyncWorkspacesPost(requestParameters: SyncDocumentWorkspacesWorkspacesWorkspaceIdDocumentsSyncWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.syncDocumentWorkspacesWorkspacesWorkspaceIdDocumentsSyncWorkspacesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Workspace operations using internal IDs.
     * Update Document Workspaces
     */
    async updateDocumentWorkspacesApiV1WorkspacesWorkspaceIdDocumentsUpdateWorkspacesPostRaw(requestParameters: UpdateDocumentWorkspacesWorkspacesWorkspaceIdDocumentsUpdateWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateDocumentWorkspacesApiV1WorkspacesWorkspaceIdDocumentsUpdateWorkspacesPost().'
            );
        }

        if (requestParameters['documentWorkspaceUpdate'] == null) {
            throw new runtime.RequiredError(
                'documentWorkspaceUpdate',
                'Required parameter "documentWorkspaceUpdate" was null or undefined when calling updateDocumentWorkspacesApiV1WorkspacesWorkspaceIdDocumentsUpdateWorkspacesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/documents/update-workspaces`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentWorkspaceUpdateToJSON(requestParameters['documentWorkspaceUpdate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Workspace operations using internal IDs.
     * Update Document Workspaces
     */
    async updateDocumentWorkspacesApiV1WorkspacesWorkspaceIdDocumentsUpdateWorkspacesPost(requestParameters: UpdateDocumentWorkspacesWorkspacesWorkspaceIdDocumentsUpdateWorkspacesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateDocumentWorkspacesApiV1WorkspacesWorkspaceIdDocumentsUpdateWorkspacesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Document
     */
    async uploadDocumentApiV1WorkspacesWorkspaceIdUploadPostRaw(requestParameters: UploadDocumentWorkspacesWorkspaceIdUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling uploadDocumentApiV1WorkspacesWorkspaceIdUploadPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadDocumentApiV1WorkspacesWorkspaceIdUploadPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['strategy'] != null) {
            queryParameters['strategy'] = requestParameters['strategy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/workspaces/{workspace_id}/upload`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Upload Document
     */
    async uploadDocumentApiV1WorkspacesWorkspaceIdUploadPost(requestParameters: UploadDocumentWorkspacesWorkspaceIdUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.uploadDocumentApiV1WorkspacesWorkspaceIdUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
