/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AppResponseFromJSON,
    AppResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GlobalSearchWorkspacesWorkspaceIdSearchGetRequest {
    workspaceId: string;
    q: string;
}

export interface VectorSearchWorkspacesWorkspaceIdSearchVectorGetRequest {
    workspaceId: string;
    q: string;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Perform a unified search across all architectural entities.
     * Global Search
     */
    async globalSearchWorkspacesWorkspaceIdSearchGetRaw(requestParameters: GlobalSearchWorkspacesWorkspaceIdSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling globalSearchWorkspacesWorkspaceIdSearchGet().'
            );
        }

        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling globalSearchWorkspacesWorkspaceIdSearchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/search/`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Perform a unified search across all architectural entities.
     * Global Search
     */
    async globalSearchWorkspacesWorkspaceIdSearchGet(requestParameters: GlobalSearchWorkspacesWorkspaceIdSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.globalSearchWorkspacesWorkspaceIdSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Perform a semantic search in the specific workspace using the RAG pipeline.
     * Vector Search
     */
    async vectorSearchWorkspacesWorkspaceIdSearchVectorGetRaw(requestParameters: VectorSearchWorkspacesWorkspaceIdSearchVectorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling vectorSearchWorkspacesWorkspaceIdSearchVectorGet().'
            );
        }

        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling vectorSearchWorkspacesWorkspaceIdSearchVectorGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/search/vector`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Perform a semantic search in the specific workspace using the RAG pipeline.
     * Vector Search
     */
    async vectorSearchWorkspacesWorkspaceIdSearchVectorGet(requestParameters: VectorSearchWorkspacesWorkspaceIdSearchVectorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.vectorSearchWorkspacesWorkspaceIdSearchVectorGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
