/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetSettingsSettingsGetRequest {
    workspaceId?: string | null;
}

export interface UpdateSettingsSettingsPatchRequest {
    requestBody: { [key: string]: any; };
    workspaceId?: string | null;
}

/**
 * 
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     * Get metadata describing setting field properties and editability.
     * Get Settings Metadata
     */
    async getSettingsMetadataSettingsMetadataGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/settings/metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get metadata describing setting field properties and editability.
     * Get Settings Metadata
     */
    async getSettingsMetadataSettingsMetadataGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSettingsMetadataSettingsMetadataGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get settings for a specific workspace or global defaults.
     * Get Settings
     */
    async getSettingsSettingsGetRaw(requestParameters: GetSettingsSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/settings/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get settings for a specific workspace or global defaults.
     * Get Settings
     */
    async getSettingsSettingsGet(requestParameters: GetSettingsSettingsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSettingsSettingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update settings for a specific workspace or global defaults.
     * Update Settings
     */
    async updateSettingsSettingsPatchRaw(requestParameters: UpdateSettingsSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateSettingsSettingsPatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/settings/`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update settings for a specific workspace or global defaults.
     * Update Settings
     */
    async updateSettingsSettingsPatch(requestParameters: UpdateSettingsSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateSettingsSettingsPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
