/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetSettingsMetadataWorkspacesWorkspaceIdSettingsMetadataGetRequest {
    workspaceId: string;
}

export interface GetSettingsWorkspacesWorkspaceIdSettingsGetRequest {
    workspaceId: string;
}

export interface UpdateSettingsWorkspacesWorkspaceIdSettingsPatchRequest {
    workspaceId: string;
    requestBody: { [key: string]: any; };
}

/**
 * 
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     * Get metadata describing setting field properties and editability.
     * Get Settings Metadata
     */
    async getSettingsMetadataWorkspacesWorkspaceIdSettingsMetadataGetRaw(requestParameters: GetSettingsMetadataWorkspacesWorkspaceIdSettingsMetadataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getSettingsMetadataWorkspacesWorkspaceIdSettingsMetadataGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/settings/metadata`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get metadata describing setting field properties and editability.
     * Get Settings Metadata
     */
    async getSettingsMetadataWorkspacesWorkspaceIdSettingsMetadataGet(requestParameters: GetSettingsMetadataWorkspacesWorkspaceIdSettingsMetadataGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSettingsMetadataWorkspacesWorkspaceIdSettingsMetadataGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get settings for a specific workspace.
     * Get Settings
     */
    async getSettingsWorkspacesWorkspaceIdSettingsGetRaw(requestParameters: GetSettingsWorkspacesWorkspaceIdSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getSettingsWorkspacesWorkspaceIdSettingsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/settings/`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get settings for a specific workspace.
     * Get Settings
     */
    async getSettingsWorkspacesWorkspaceIdSettingsGet(requestParameters: GetSettingsWorkspacesWorkspaceIdSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSettingsWorkspacesWorkspaceIdSettingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update settings for a specific workspace.
     * Update Settings
     */
    async updateSettingsWorkspacesWorkspaceIdSettingsPatchRaw(requestParameters: UpdateSettingsWorkspacesWorkspaceIdSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateSettingsWorkspacesWorkspaceIdSettingsPatch().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateSettingsWorkspacesWorkspaceIdSettingsPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/settings/`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update settings for a specific workspace.
     * Update Settings
     */
    async updateSettingsWorkspacesWorkspaceIdSettingsPatch(requestParameters: UpdateSettingsWorkspacesWorkspaceIdSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateSettingsWorkspacesWorkspaceIdSettingsPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
