/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Workspace } from './Workspace';
import {
    WorkspaceFromJSON,
    WorkspaceFromJSONTyped,
    WorkspaceToJSON,
    WorkspaceToJSONTyped,
} from './Workspace';

/**
 * 
 * @export
 * @interface AppResponseListWorkspace
 */
export interface AppResponseListWorkspace {
    /**
     * 
     * @type {boolean}
     * @memberof AppResponseListWorkspace
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppResponseListWorkspace
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof AppResponseListWorkspace
     */
    message?: string;
    /**
     * 
     * @type {Array<Workspace>}
     * @memberof AppResponseListWorkspace
     */
    data?: Array<Workspace> | null;
}

/**
 * Check if a given object implements the AppResponseListWorkspace interface.
 */
export function instanceOfAppResponseListWorkspace(value: object): value is AppResponseListWorkspace {
    return true;
}

export function AppResponseListWorkspaceFromJSON(json: any): AppResponseListWorkspace {
    return AppResponseListWorkspaceFromJSONTyped(json, false);
}

export function AppResponseListWorkspaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppResponseListWorkspace {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(WorkspaceFromJSON)),
    };
}

export function AppResponseListWorkspaceToJSON(json: any): AppResponseListWorkspace {
    return AppResponseListWorkspaceToJSONTyped(json, false);
}

export function AppResponseListWorkspaceToJSONTyped(value?: AppResponseListWorkspace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(WorkspaceToJSON)),
    };
}

