/* tslint:disable */
/* eslint-disable */
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, FromJSON, ToJSON } from '../runtime';
/**
 * 
 * @export
 * @interface AppResponse
 */
export interface AppResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AppResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof AppResponse
     */
    message?: string;
    /**
     * 
     * @type {}
     * @memberof AppResponse
     */
    data?:  | null;
}

/**
 * Check if a given object implements the AppResponse interface.
 */
export function instanceOfAppResponse(value: object): value is AppResponse {
    return true;
}

export function AppResponseFromJSON(json: any): AppResponse {
    return AppResponseFromJSONTyped(json, false);
}

export function AppResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : FromJSON(json['data']),
    };
}

export function AppResponseToJSON(json: any): AppResponse {
    return AppResponseToJSONTyped(json, false);
}

export function AppResponseToJSONTyped(value?: AppResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': ToJSON(value['data']),
    };
}

