/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface AppResponseUser
 */
export interface AppResponseUser {
    /**
     * 
     * @type {boolean}
     * @memberof AppResponseUser
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppResponseUser
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof AppResponseUser
     */
    message?: string;
    /**
     * 
     * @type {User}
     * @memberof AppResponseUser
     */
    data?: User | null;
}

/**
 * Check if a given object implements the AppResponseUser interface.
 */
export function instanceOfAppResponseUser(value: object): value is AppResponseUser {
    return true;
}

export function AppResponseUserFromJSON(json: any): AppResponseUser {
    return AppResponseUserFromJSONTyped(json, false);
}

export function AppResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UserFromJSON(json['data']),
    };
}

export function AppResponseUserToJSON(json: any): AppResponseUser {
    return AppResponseUserToJSONTyped(json, false);
}

export function AppResponseUserToJSONTyped(value?: AppResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': UserToJSON(value['data']),
    };
}

