/* tslint:disable */
/* eslint-disable */
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatStreamRequest
 */
export interface ChatStreamRequest {
    /**
     * The user message to process
     * @type {string}
     * @memberof ChatStreamRequest
     */
    message: string;
    /**
     * The ID of the chat thread
     * @type {string}
     * @memberof ChatStreamRequest
     */
    threadId: string;
    /**
     * The workspace ID context
     * @type {string}
     * @memberof ChatStreamRequest
     */
    workspaceId?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ChatStreamRequest
     */
    execution?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ChatStreamRequest interface.
 */
export function instanceOfChatStreamRequest(value: object): value is ChatStreamRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    return true;
}

export function ChatStreamRequestFromJSON(json: any): ChatStreamRequest {
    return ChatStreamRequestFromJSONTyped(json, false);
}

export function ChatStreamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatStreamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'threadId': json['thread_id'],
        'workspaceId': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'execution': json['execution'] == null ? undefined : json['execution'],
    };
}

export function ChatStreamRequestToJSON(json: any): ChatStreamRequest {
    return ChatStreamRequestToJSONTyped(json, false);
}

export function ChatStreamRequestToJSONTyped(value?: ChatStreamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'thread_id': value['threadId'],
        'workspace_id': value['workspaceId'],
        'execution': value['execution'],
    };
}

