/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentWorkspaceUpdate
 */
export interface DocumentWorkspaceUpdate {
    /**
     * 
     * @type {string}
     * @memberof DocumentWorkspaceUpdate
     */
    documentId: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentWorkspaceUpdate
     */
    targetWorkspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentWorkspaceUpdate
     */
    action?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentWorkspaceUpdate
     */
    forceReindex?: boolean;
}

/**
 * Check if a given object implements the DocumentWorkspaceUpdate interface.
 */
export function instanceOfDocumentWorkspaceUpdate(value: object): value is DocumentWorkspaceUpdate {
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('targetWorkspaceId' in value) || value['targetWorkspaceId'] === undefined) return false;
    return true;
}

export function DocumentWorkspaceUpdateFromJSON(json: any): DocumentWorkspaceUpdate {
    return DocumentWorkspaceUpdateFromJSONTyped(json, false);
}

export function DocumentWorkspaceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentWorkspaceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'documentId': json['document_id'],
        'targetWorkspaceId': json['target_workspace_id'],
        'action': json['action'] == null ? undefined : json['action'],
        'forceReindex': json['force_reindex'] == null ? undefined : json['force_reindex'],
    };
}

export function DocumentWorkspaceUpdateToJSON(json: any): DocumentWorkspaceUpdate {
    return DocumentWorkspaceUpdateToJSONTyped(json, false);
}

export function DocumentWorkspaceUpdateToJSONTyped(value?: DocumentWorkspaceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document_id': value['documentId'],
        'target_workspace_id': value['targetWorkspaceId'],
        'action': value['action'],
        'force_reindex': value['forceReindex'],
    };
}

