/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitHubImportRequest
 */
export interface GitHubImportRequest {
    /**
     * GitHub repository URL
     * @type {string}
     * @memberof GitHubImportRequest
     */
    url: string;
    /**
     * Branch name
     * @type {string}
     * @memberof GitHubImportRequest
     */
    branch?: string;
}

/**
 * Check if a given object implements the GitHubImportRequest interface.
 */
export function instanceOfGitHubImportRequest(value: object): value is GitHubImportRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function GitHubImportRequestFromJSON(json: any): GitHubImportRequest {
    return GitHubImportRequestFromJSONTyped(json, false);
}

export function GitHubImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitHubImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'branch': json['branch'] == null ? undefined : json['branch'],
    };
}

export function GitHubImportRequestToJSON(json: any): GitHubImportRequest {
    return GitHubImportRequestToJSONTyped(json, false);
}

export function GitHubImportRequestToJSONTyped(value?: GitHubImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'branch': value['branch'],
    };
}

