/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitemapImportRequest
 */
export interface SitemapImportRequest {
    /**
     * Sitemap URL
     * @type {string}
     * @memberof SitemapImportRequest
     */
    url: string;
}

/**
 * Check if a given object implements the SitemapImportRequest interface.
 */
export function instanceOfSitemapImportRequest(value: object): value is SitemapImportRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function SitemapImportRequestFromJSON(json: any): SitemapImportRequest {
    return SitemapImportRequestFromJSONTyped(json, false);
}

export function SitemapImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitemapImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function SitemapImportRequestToJSON(json: any): SitemapImportRequest {
    return SitemapImportRequestToJSONTyped(json, false);
}

export function SitemapImportRequestToJSONTyped(value?: SitemapImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

