/* tslint:disable */
/* eslint-disable */
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadTitleUpdate
 */
export interface ThreadTitleUpdate {
    /**
     * 
     * @type {string}
     * @memberof ThreadTitleUpdate
     */
    title: string;
}

/**
 * Check if a given object implements the ThreadTitleUpdate interface.
 */
export function instanceOfThreadTitleUpdate(value: object): value is ThreadTitleUpdate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ThreadTitleUpdateFromJSON(json: any): ThreadTitleUpdate {
    return ThreadTitleUpdateFromJSONTyped(json, false);
}

export function ThreadTitleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadTitleUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function ThreadTitleUpdateToJSON(json: any): ThreadTitleUpdate {
    return ThreadTitleUpdateToJSONTyped(json, false);
}

export function ThreadTitleUpdateToJSONTyped(value?: ThreadTitleUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

