/* tslint:disable */
 
/**
 * Knowledge Bank API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolDefinition
 */
export interface ToolDefinition {
    /**
     * 
     * @type {string}
     * @memberof ToolDefinition
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ToolDefinition
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ToolDefinition
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ToolDefinition
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ToolDefinition
     */
    enabled?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ToolDefinition
     */
    config?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ToolDefinition interface.
 */
export function instanceOfToolDefinition(value: object): value is ToolDefinition {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ToolDefinitionFromJSON(json: any): ToolDefinition {
    return ToolDefinitionFromJSONTyped(json, false);
}

export function ToolDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function ToolDefinitionToJSON(json: any): ToolDefinition {
    return ToolDefinitionToJSONTyped(json, false);
}

export function ToolDefinitionToJSONTyped(value?: ToolDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'enabled': value['enabled'],
        'config': value['config'],
    };
}

