/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceStats
 */
export interface WorkspaceStats {
    /**
     * 
     * @type {number}
     * @memberof WorkspaceStats
     */
    thread_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceStats
     */
    doc_count?: number;
}

/**
 * Check if a given object implements the WorkspaceStats interface.
 */
export function instanceOfWorkspaceStats(value: object): value is WorkspaceStats {
    return true;
}

export function WorkspaceStatsFromJSON(json: any): WorkspaceStats {
    return WorkspaceStatsFromJSONTyped(json, false);
}

export function WorkspaceStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceStats {
    if (json == null) {
        return json;
    }
    return {
        
        'thread_count': json['thread_count'] == null ? undefined : json['thread_count'],
        'doc_count': json['doc_count'] == null ? undefined : json['doc_count'],
    };
}

export function WorkspaceStatsToJSON(json: any): WorkspaceStats {
    return WorkspaceStatsToJSONTyped(json, false);
}

export function WorkspaceStatsToJSONTyped(value?: WorkspaceStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thread_count': value['thread_count'],
        'doc_count': value['doc_count'],
    };
}

