/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppResponse,
  ChatStreamRequest,
  HTTPValidationError,
  ThreadTitleUpdate,
} from '../models/index';
import {
    AppResponseFromJSON,
    AppResponseToJSON,
    ChatStreamRequestFromJSON,
    ChatStreamRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ThreadTitleUpdateFromJSON,
    ThreadTitleUpdateToJSON,
} from '../models/index';

export interface ChatStreamWorkspacesWorkspaceIdChatStreamPostRequest {
    workspaceId: string;
    chatStreamRequest: ChatStreamRequest;
}

export interface DeleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDeleteRequest {
    threadId: string;
    workspaceId: string;
}

export interface GetChatHistoryWorkspacesWorkspaceIdChatHistoryThreadIdGetRequest {
    threadId: string;
    workspaceId: string;
}

export interface GetThreadWorkspacesWorkspaceIdChatThreadsThreadIdGetRequest {
    threadId: string;
    workspaceId: string;
}

export interface ListChatThreadsWorkspacesWorkspaceIdChatThreadsGetRequest {
    workspaceId: string;
}

export interface UpdateThreadTitleWorkspacesWorkspaceIdChatThreadsThreadIdTitlePatchRequest {
    threadId: string;
    workspaceId: string;
    threadTitleUpdate: ThreadTitleUpdate;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Stream chat updates using SSE. Spawns background title generation for consistent UX.
     * Chat Stream
     */
    async chatStreamWorkspacesWorkspaceIdChatStreamPostRaw(requestParameters: ChatStreamWorkspacesWorkspaceIdChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling chatStreamWorkspacesWorkspaceIdChatStreamPost().'
            );
        }

        if (requestParameters['chatStreamRequest'] == null) {
            throw new runtime.RequiredError(
                'chatStreamRequest',
                'Required parameter "chatStreamRequest" was null or undefined when calling chatStreamWorkspacesWorkspaceIdChatStreamPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/chat/stream`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatStreamRequestToJSON(requestParameters['chatStreamRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stream chat updates using SSE. Spawns background title generation for consistent UX.
     * Chat Stream
     */
    async chatStreamWorkspacesWorkspaceIdChatStreamPost(requestParameters: ChatStreamWorkspacesWorkspaceIdChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.chatStreamWorkspacesWorkspaceIdChatStreamPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Thread
     */
    async deleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDeleteRaw(requestParameters: DeleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling deleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDelete().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/chat/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Delete Thread
     */
    async deleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDelete(requestParameters: DeleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.deleteThreadWorkspacesWorkspaceIdChatThreadsThreadIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Chat History
     */
    async getChatHistoryApiV1WorkspacesWorkspaceIdChatHistoryThreadIdGetRaw(requestParameters: GetChatHistoryWorkspacesWorkspaceIdChatHistoryThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getChatHistoryApiV1WorkspacesWorkspaceIdChatHistoryThreadIdGet().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getChatHistoryApiV1WorkspacesWorkspaceIdChatHistoryThreadIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/chat/history/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Get Chat History
     */
    async getChatHistoryApiV1WorkspacesWorkspaceIdChatHistoryThreadIdGet(requestParameters: GetChatHistoryWorkspacesWorkspaceIdChatHistoryThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.getChatHistoryApiV1WorkspacesWorkspaceIdChatHistoryThreadIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Thread
     */
    async getThreadApiV1WorkspacesWorkspaceIdChatThreadsThreadIdGetRaw(requestParameters: GetThreadWorkspacesWorkspaceIdChatThreadsThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getThreadApiV1WorkspacesWorkspaceIdChatThreadsThreadIdGet().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getThreadApiV1WorkspacesWorkspaceIdChatThreadsThreadIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/chat/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Get Thread
     */
    async getThreadApiV1WorkspacesWorkspaceIdChatThreadsThreadIdGet(requestParameters: GetThreadWorkspacesWorkspaceIdChatThreadsThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.getThreadApiV1WorkspacesWorkspaceIdChatThreadsThreadIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Chat Threads
     */
    async listChatThreadsApiV1WorkspacesWorkspaceIdChatThreadsGetRaw(requestParameters: ListChatThreadsWorkspacesWorkspaceIdChatThreadsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listChatThreadsApiV1WorkspacesWorkspaceIdChatThreadsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/chat/threads`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * List Chat Threads
     */
    async listChatThreadsApiV1WorkspacesWorkspaceIdChatThreadsGet(requestParameters: ListChatThreadsWorkspacesWorkspaceIdChatThreadsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.listChatThreadsApiV1WorkspacesWorkspaceIdChatThreadsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Thread Title
     */
    async updateThreadTitleApiV1WorkspacesWorkspaceIdChatThreadsThreadIdTitlePatchRaw(requestParameters: UpdateThreadTitleWorkspacesWorkspaceIdChatThreadsThreadIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateThreadTitleApiV1WorkspacesWorkspaceIdChatThreadsThreadIdTitlePatch().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateThreadTitleApiV1WorkspacesWorkspaceIdChatThreadsThreadIdTitlePatch().'
            );
        }

        if (requestParameters['threadTitleUpdate'] == null) {
            throw new runtime.RequiredError(
                'threadTitleUpdate',
                'Required parameter "threadTitleUpdate" was null or undefined when calling updateThreadTitleApiV1WorkspacesWorkspaceIdChatThreadsThreadIdTitlePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/chat/threads/{thread_id}/title`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ThreadTitleUpdateToJSON(requestParameters['threadTitleUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppResponseFromJSON(jsonValue));
    }

    /**
     * Update Thread Title
     */
    async updateThreadTitleApiV1WorkspacesWorkspaceIdChatThreadsThreadIdTitlePatch(requestParameters: UpdateThreadTitleWorkspacesWorkspaceIdChatThreadsThreadIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppResponse> {
        const response = await this.updateThreadTitleApiV1WorkspacesWorkspaceIdChatThreadsThreadIdTitlePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
