/* tslint:disable */
/* eslint-disable */
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateDatasetEvalDatasetsPostRequest {
    workspaceId?: string;
}

export interface GetRunEvalRunsRunIdGetRequest {
    runId: string;
}

export interface ListDatasetsEvalDatasetsGetRequest {
    workspaceId?: string;
}

export interface ListRunsEvalRunsGetRequest {
    workspaceId?: string;
}

export interface RunEvaluationEvalRunsPostRequest {
    workspaceId?: string;
}

/**
 * 
 */
export class EvaluationApi extends runtime.BaseAPI {

    /**
     * Create Dataset
     */
    async createDatasetEvalDatasetsPostRaw(requestParameters: CreateDatasetEvalDatasetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/eval/datasets`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Dataset
     */
    async createDatasetEvalDatasetsPost(requestParameters: CreateDatasetEvalDatasetsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createDatasetEvalDatasetsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Run
     */
    async getRunEvalRunsRunIdGetRaw(requestParameters: GetRunEvalRunsRunIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getRunEvalRunsRunIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/eval/runs/{run_id}`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Run
     */
    async getRunEvalRunsRunIdGet(requestParameters: GetRunEvalRunsRunIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getRunEvalRunsRunIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Datasets
     */
    async listDatasetsEvalDatasetsGetRaw(requestParameters: ListDatasetsEvalDatasetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/eval/datasets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Datasets
     */
    async listDatasetsEvalDatasetsGet(requestParameters: ListDatasetsEvalDatasetsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listDatasetsEvalDatasetsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Runs
     */
    async listRunsEvalRunsGetRaw(requestParameters: ListRunsEvalRunsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/eval/runs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Runs
     */
    async listRunsEvalRunsGet(requestParameters: ListRunsEvalRunsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listRunsEvalRunsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Run Evaluation
     */
    async runEvaluationEvalRunsPostRaw(requestParameters: RunEvaluationEvalRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspace_id'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/eval/runs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Run Evaluation
     */
    async runEvaluationEvalRunsPost(requestParameters: RunEvaluationEvalRunsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.runEvaluationEvalRunsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
