/* tslint:disable */
 
/**
 * Karag API
 * Modular RAG & Agentic Chatbot API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CancelTaskWorkspacesWorkspaceIdTasksTaskIdCancelPostRequest {
    taskId: string;
    workspaceId: string;
}

export interface CleanupTasksWorkspacesWorkspaceIdTasksCleanupDeleteRequest {
    workspaceId: string;
    olderThanHours?: number;
}

export interface GetTaskStatusWorkspacesWorkspaceIdTasksTaskIdGetRequest {
    taskId: string;
    workspaceId: string;
}

export interface ListTasksWorkspacesWorkspaceIdTasksGetRequest {
    workspaceId: string;
    type?: string;
    limit?: number;
}

export interface RetryTaskWorkspacesWorkspaceIdTasksTaskIdRetryPostRequest {
    taskId: string;
    workspaceId: string;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Cancel a pending or processing task.
     * Cancel Task
     */
    async cancelTaskApiV1WorkspacesWorkspaceIdTasksTaskIdCancelPostRaw(requestParameters: CancelTaskWorkspacesWorkspaceIdTasksTaskIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling cancelTaskApiV1WorkspacesWorkspaceIdTasksTaskIdCancelPost().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling cancelTaskApiV1WorkspacesWorkspaceIdTasksTaskIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/tasks/{task_id}/cancel`;
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Cancel a pending or processing task.
     * Cancel Task
     */
    async cancelTaskApiV1WorkspacesWorkspaceIdTasksTaskIdCancelPost(requestParameters: CancelTaskWorkspacesWorkspaceIdTasksTaskIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.cancelTaskApiV1WorkspacesWorkspaceIdTasksTaskIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove completed/failed tasks older than the given number of hours.
     * Cleanup Tasks
     */
    async cleanupTasksWorkspacesWorkspaceIdTasksCleanupDeleteRaw(requestParameters: CleanupTasksWorkspacesWorkspaceIdTasksCleanupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling cleanupTasksWorkspacesWorkspaceIdTasksCleanupDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['olderThanHours'] != null) {
            queryParameters['older_than_hours'] = requestParameters['olderThanHours'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/tasks/cleanup`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Remove completed/failed tasks older than the given number of hours.
     * Cleanup Tasks
     */
    async cleanupTasksWorkspacesWorkspaceIdTasksCleanupDelete(requestParameters: CleanupTasksWorkspacesWorkspaceIdTasksCleanupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.cleanupTasksWorkspacesWorkspaceIdTasksCleanupDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the current status of a specific task.
     * Get Task Status
     */
    async getTaskStatusWorkspacesWorkspaceIdTasksTaskIdGetRaw(requestParameters: GetTaskStatusWorkspacesWorkspaceIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getTaskStatusWorkspacesWorkspaceIdTasksTaskIdGet().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getTaskStatusWorkspacesWorkspaceIdTasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get the current status of a specific task.
     * Get Task Status
     */
    async getTaskStatusWorkspacesWorkspaceIdTasksTaskIdGet(requestParameters: GetTaskStatusWorkspacesWorkspaceIdTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getTaskStatusWorkspacesWorkspaceIdTasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List tasks for the current workspace.
     * List Tasks
     */
    async listTasksApiV1WorkspacesWorkspaceIdTasksGetRaw(requestParameters: ListTasksWorkspacesWorkspaceIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listTasksApiV1WorkspacesWorkspaceIdTasksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/tasks/`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List tasks for the current workspace.
     * List Tasks
     */
    async listTasksApiV1WorkspacesWorkspaceIdTasksGet(requestParameters: ListTasksWorkspacesWorkspaceIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listTasksApiV1WorkspacesWorkspaceIdTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Mark a failed task as retryable and re-dispatch it to background workers.
     * Retry Task
     */
    async retryTaskApiV1WorkspacesWorkspaceIdTasksTaskIdRetryPostRaw(requestParameters: RetryTaskWorkspacesWorkspaceIdTasksTaskIdRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling retryTaskApiV1WorkspacesWorkspaceIdTasksTaskIdRetryPost().'
            );
        }

        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling retryTaskApiV1WorkspacesWorkspaceIdTasksTaskIdRetryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/workspaces/{workspace_id}/tasks/{task_id}/retry`;
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Mark a failed task as retryable and re-dispatch it to background workers.
     * Retry Task
     */
    async retryTaskApiV1WorkspacesWorkspaceIdTasksTaskIdRetryPost(requestParameters: RetryTaskWorkspacesWorkspaceIdTasksTaskIdRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.retryTaskApiV1WorkspacesWorkspaceIdTasksTaskIdRetryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
