from enum import StrEnum


class AppErrorCode(StrEnum):
    # Task & Jobs
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_ALREADY_FAILED = "TASK_ALREADY_FAILED"

    # Ingestion Errors
    INGEST_FAILED = "INGEST_FAILED"
    FILE_READ_ERROR = "FILE_READ_ERROR"
    URL_FETCH_FAILED = "URL_FETCH_FAILED"
    GITHUB_IMPORT_FAILED = "GITHUB_IMPORT_FAILED"
    SITEMAP_FETCH_FAILED = "SITEMAP_FETCH_FAILED"
    DIRECTORY_NOT_FOUND = "DIRECTORY_NOT_FOUND"
    AUDIO_PROCESSING_FAILED = "AUDIO_PROCESSING_FAILED"

    # Vector DB & Search
    INDEXING_FAILED = "INDEXING_FAILED"
    SEARCH_FAILED = "SEARCH_FAILED"
    COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND"

    # Graph Engine
    GRAPH_EXTRACTION_FAILED = "GRAPH_EXTRACTION_FAILED"
    NEO4J_CONNECTION_ERROR = "NEO4J_CONNECTION_ERROR"

    # Workspace & Settings
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    DUPLICATE_WORKSPACE = "DUPLICATE_WORKSPACE"
    INVALID_SETTINGS = "INVALID_SETTINGS"
    IMMUTABLE_FIELD_UPDATE = "IMMUTABLE_FIELD_UPDATE"

    # Infrastructure
    MINIO_UPLOAD_FAILED = "MINIO_UPLOAD_FAILED"
    MONGODB_ERROR = "MONGODB_ERROR"
